# Generated by Django 5.2.6 on 2025-09-06 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('blood_group', models.CharField(max_length=10)),
                ('post_code', models.CharField(max_length=20)),
                ('post_office', models.CharField(max_length=100)),
                ('upozilla', models.CharField(max_length=100)),
                ('zila', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('president', 'President'), ('chairman', 'Chairman'), ('member', 'Member')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
